server:
  port: 6666

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eliboy
    username: postgres
    password: 20012023
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: true


springdoc:
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
  api-docs:
    path: /api/docs